### ISSUE TITLE
question / training

### ISSUE THREAD

**Issue by 1N50MN14** [junrushao1994/fast-neural-style.tf#1]
First thanks for the great work and putting up the repo! ;) 

I was wondering if there are any advantages, namely speed, to using TS vs Torch (say jcjohnson's feedforward  implementation) and what is your ETA on training if I may ask?

**Comment by junrushao** [comment]
Thank you so much for your issue.

I have not benchmarked TF vs Torch in this task. Theoretically, I think their training speed should be comparable. Also, the ETA depends on many factors like GPU, cudnn and disk. It took me 3-4 hours on a server with old TITAN X, official TF r0.11rc0, cudnn 5.1, cuda 7.5, HDD.

**Comment by 1N50MN14** [comment]
@junrushao1994 Awesome thank you for the reply, what's your ETA on the training script if I may ask? I was also wondering about the meaning of the --arch argument.. finally,  my understanding from jcjohnson's repo is that when applying a style on a sequence of images, applying it on subsequent images (after the first one) is faster - is this is the case here or the speed is equally the same (if so then I can distribute the load over multiple machines/GPU's)

Thank you ;)

**Comment by junrushao** [comment]
@1N50MN14 Hi, thank you for asking :)
- It took me 3-4 hours on a old TITAN X GPU for training. (I have not released the training script since I would like to support more options in the future).
- To my knowledge, the --arch argument in jcjohnson's repo defines the generator network architecture. If you are interested, you can refer to his [script](https://github.com/jcjohnson/fast-neural-style/blob/master/fast_neural_style/models.lua#L62-L135) for details. 
- Applying a style on the subsequent images after the first one is faster (due to reading models from disks and the lazy allocation of GPU memory, etc).

**Comment by 1N50MN14** [comment]
@junrushao1994 Ok so I finally managed to install the repo things were much more straight forward thanks to TS's Dockerfile (vs all of the hassle with the Torch installation). I'm trying to test this on a 32 vCPU machine. Few things I was wondering if I could get some help:
1. My command line is something like `python render.py --input /tmp/ffcea696-1390-400f-8444-72214c41bc80/frame-0001.jpg --output /tmp/ffcea696-1390-400f-8444-72214c41bc80/out/frame-0001.jpg --model wave` but the script is throwing an error `ValueError: Restore called with invalid save path: 'wave'. File path is: 'wave'` even though I'm clearly specifying the input and output path. (also tried wave.model)
2. I didn't quite know what to use as the --arch value (apologies python is not my thing) so I left it out, I guess that defaults to cpu mode?
3.  You mentioned that applying a style on subsequent images is faster, but looking at the script I don't see that it accepts `input_dir` or an array of strings? 
4. `render.py` assumes that it's being called from the code's root directly and attempts to load the model from `./models`\- would it be possible to pass a model path instead (or as an alternative)? I basically call it through an external script and listen to stdout instead..

Thank you once again, I was very surprised by the smooth installation... crossing my fingers ts will properly utilise multi-cpu...

Thanks again ;)

**Comment by junrushao** [comment]
Thank you for your response.
1. You should use "--model ./models/wave.model"
2. But I have no such --arch flag, and the --arch flag in jcjohnson's repo means the structure of neural network, not CPU or GPU. Please just forget it :)
3. You can modify the program your self.
4. Please refer to 1.

**Comment by 1N50MN14** [comment]
@junrushao1994 The  "--model ./models/wave.model" did it!

450x800 pixels image, 20vCPU / 32gb memory results:
First time. Time used:  1.51801991463
Second time. Time used:  1.48423099518

That sounds more like it!

I'm really impressed by your work and how relatively straight forward it was to set the whole thing up.. really well done!

Now I'm going to start nagging on the training script (just kidding, but soon!) :) :) 

Thanks again!

**Comment by junrushao** [comment]
Thank you for your comments. Currently I am a little bit swamped in person issues. Hopefully I will consider to sort out these stuff soon :)

**Comment by 1N50MN14** [comment]
@junrushao1994 Just a quick note, it seems `render.py` is not utilising all CPUs, by the looks of only 2 of them are being used, not sure if this is related to the script itself or TS

**Comment by junrushao** [comment]
@1N50MN14 It is not related to the script. TensorFlow will automatically take care of this. Thank you!
