### ISSUE TITLE
Got an error

### ISSUE THREAD

**Issue by bamboowind** [junrushao1994/fast-neural-style.tf#2]
command like this: python render.py --input ./examples/inputs/aaa.jpg --output profile.jpg --model ./models/cubist.model
then got an error: TypeError: import_meta_graph() got an unexpected keyword argument 'clear_deivces'

What's the version of tensorflow are you using?

**Comment by junrushao** [comment]
Hi, I am using r0.11. Please refer to https://www.tensorflow.org/versions/r0.11/api_docs/python/state_ops.html#import_meta_graph for details.
