### ISSUE TITLE
zero padding

### ISSUE THREAD

**Issue by caijunhao** [junrushao1994/fast-neural-style.tf#3]
Hi, @junrushao1994 
How can you avoid the zero padding effect since tensorflow only have zero padding when using convolution operation?

**Comment by junrushao** [comment]
@caijunhao Hi, I use reflect padding

**Comment by caijunhao** [comment]
@junrushao1994  Thank you for your reply :D.
How can I use reflect padding in tensorflow,which operation?

**Comment by caijunhao** [comment]
@junrushao1994  Thank you for your reply :D.
How can I use reflect padding in tensorflow,which operation?

**Comment by caijunhao** [comment]
Using tf.pad() can avoid zero padding effect.
